import { Project } from '@/types'

export const projects: Project[] = [
  {
    id: 1,
    title: 'Expanding Cards',
    slug: 'expanding-cards',
    description: 'Click a panel to expand it while others collapse smoothly',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useState', 'Flexbox', 'CSS transitions'],
  },
  {
    id: 2,
    title: 'Progress Steps',
    slug: 'progress-steps',
    description: 'Multi-step progress bar with next and previous navigation',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useState', 'dynamic classes'],
  },
  {
    id: 3,
    title: 'Rotating Navigation',
    slug: 'rotating-navigation',
    description: 'Navigation that rotates the whole page when opened',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useState', 'CSS transform', 'rotate'],
  },
  {
    id: 4,
    title: 'Hidden Search Widget',
    slug: 'hidden-search',
    description: 'Search bar that expands on button click',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useState', 'CSS transitions', 'input'],
  },
  {
    id: 5,
    title: 'Blurry Loading',
    slug: 'blurry-loading',
    description: 'Background image sharpens as a fake loading counter ticks up',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useEffect', 'CSS filter', 'setInterval'],
  },
  {
    id: 6,
    title: 'Scroll Animation',
    slug: 'scroll-animation',
    description: 'Elements animate into view as you scroll down the page',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useEffect', 'IntersectionObserver', 'scroll'],
  },
  {
    id: 7,
    title: 'Split Landing Page',
    slug: 'split-landing-page',
    description: 'Hover left or right to expand that side of the landing page',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useState', 'hover', 'CSS transitions'],
  },
  {
    id: 8,
    title: 'Form Wave',
    slug: 'form-wave',
    description: 'Form labels animate letter by letter when the input is focused',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useRef', 'CSS animation', 'forms'],
  },
  {
    id: 9,
    title: 'Sound Board',
    slug: 'sound-board',
    description: 'Buttons that play different sound effects on click',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['Audio API', 'useRef', 'events'],
  },
  {
    id: 10,
    title: 'Dad Jokes',
    slug: 'dad-jokes',
    description: 'Fetches a random dad joke from a public API',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['fetch', 'useEffect', 'API'],
  },
  {
    id: 11,
    title: 'Event Keycodes',
    slug: 'event-keycodes',
    description: 'Displays the keycode info of any key you press',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['useEffect', 'keyboard events', 'useState'],
  },
  {
    id: 12,
    title: 'FAQ Collapse',
    slug: 'faq-collapse',
    description: 'Accordion-style FAQ where clicking a question reveals the answer',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['useState', 'accordion', 'toggle'],
  },
  {
    id: 13,
    title: 'Random Choice Picker',
    slug: 'random-choice-picker',
    description: 'Enter comma-separated options and randomly pick one',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['useState', 'Math.random', 'string manipulation'],
  },
  {
    id: 14,
    title: 'Animated Navigation',
    slug: 'animated-navigation',
    description: 'Circular menu that expands with animated nav links',
    category: 'ui-animation',
    difficulty: 'intermediate',
    tags: ['useState', 'CSS clip-path', 'animation'],
  },
  {
    id: 15,
    title: 'Incrementing Counter',
    slug: 'incrementing-counter',
    description: 'Numbers count up to their target value when scrolled into view',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useEffect', 'IntersectionObserver', 'setInterval'],
  },
  {
    id: 16,
    title: 'Drink Water',
    slug: 'drink-water',
    description: 'Track your daily water intake by clicking cup buttons',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['useState', 'useMemo', 'visual feedback'],
  },
  {
    id: 17,
    title: 'Movie App',
    slug: 'movie-app',
    description: 'Search and browse movies using the TMDB API',
    category: 'apps-data',
    difficulty: 'intermediate',
    tags: ['fetch', 'API', 'search', 'useEffect'],
  },
  {
    id: 18,
    title: 'Background Slider',
    slug: 'background-slider',
    description: 'Slide through full-screen background images with arrows',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useState', 'CSS transitions', 'image slider'],
  },
  {
    id: 19,
    title: 'Theme Clock',
    slug: 'theme-clock',
    description: 'An analog + digital clock with light and dark theme toggle',
    category: 'interactivity',
    difficulty: 'intermediate',
    tags: ['useEffect', 'setInterval', 'CSS transform', 'Date API'],
  },
  {
    id: 20,
    title: 'Button Ripple Effect',
    slug: 'button-ripple-effect',
    description: 'Material Design-style ripple animation on button click',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useRef', 'mouse events', 'CSS animation'],
  },
  {
    id: 21,
    title: 'Drag N Drop',
    slug: 'drag-n-drop',
    description: 'Drag items between two columns using the HTML Drag and Drop API',
    category: 'interactivity',
    difficulty: 'intermediate',
    tags: ['Drag and Drop API', 'useState', 'useRef'],
  },
  {
    id: 22,
    title: 'Drawing App',
    slug: 'drawing-app',
    description: 'A canvas-based drawing app with color picker and brush size',
    category: 'apps-data',
    difficulty: 'intermediate',
    tags: ['Canvas API', 'useRef', 'mouse events'],
  },
  {
    id: 23,
    title: 'Kinetic Loader',
    slug: 'kinetic-loader',
    description: 'Two triangles that rotate to form a loading animation',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['CSS animation', 'keyframes', 'pure CSS'],
  },
  {
    id: 24,
    title: 'Content Placeholder',
    slug: 'content-placeholder',
    description: 'Skeleton loading screen that transitions to real content',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useEffect', 'skeleton', 'loading states'],
  },
  {
    id: 25,
    title: 'Sticky Navbar',
    slug: 'sticky-navbar',
    description: 'Navbar that changes style when you scroll past the hero section',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useEffect', 'scroll events', 'useRef'],
  },
  {
    id: 26,
    title: 'Double Vertical Slider',
    slug: 'double-vertical-slider',
    description: 'Two panels slide in opposite directions simultaneously',
    category: 'ui-animation',
    difficulty: 'intermediate',
    tags: ['useState', 'CSS transform', 'synchronized animation'],
  },
  {
    id: 27,
    title: 'Toast Notification',
    slug: 'toast-notification',
    description: 'Push notifications that slide in and auto-dismiss after 3 seconds',
    category: 'interactivity',
    difficulty: 'intermediate',
    tags: ['useState', 'useEffect', 'setTimeout', 'animation'],
  },
  {
    id: 28,
    title: 'Github Profiles',
    slug: 'github-profiles',
    description: 'Search GitHub users and display their profile card via the GitHub API',
    category: 'apps-data',
    difficulty: 'intermediate',
    tags: ['fetch', 'GitHub API', 'async/await', 'error handling'],
  },
  {
    id: 29,
    title: 'Double Click Heart',
    slug: 'double-click-heart',
    description: 'Double-click an image to trigger a heart animation like Instagram',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['useState', 'double click', 'CSS animation'],
  },
  {
    id: 30,
    title: 'Auto Text Effect',
    slug: 'auto-text-effect',
    description: 'Text types itself out one character at a time',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useEffect', 'setInterval', 'string manipulation'],
  },
  {
    id: 31,
    title: 'Password Generator',
    slug: 'password-generator',
    description: 'Generate a random password with customisable rules',
    category: 'apps-data',
    difficulty: 'intermediate',
    tags: ['useState', 'Math.random', 'clipboard API'],
  },
  {
    id: 32,
    title: 'Good Cheap Fast',
    slug: 'good-cheap-fast',
    description: 'Only 2 of 3 checkboxes can be selected at once',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['useState', 'checkbox logic', 'constraints'],
  },
  {
    id: 33,
    title: 'Notes App',
    slug: 'notes-app',
    description: 'Create, edit and delete notes that persist in localStorage',
    category: 'apps-data',
    difficulty: 'intermediate',
    tags: ['useState', 'localStorage', 'CRUD'],
  },
  {
    id: 34,
    title: 'Animated Countdown',
    slug: 'animated-countdown',
    description: 'A 3-2-1 countdown with flip animation before showing a message',
    category: 'ui-animation',
    difficulty: 'intermediate',
    tags: ['useEffect', 'setTimeout', 'CSS animation'],
  },
  {
    id: 35,
    title: 'Image Carousel',
    slug: 'image-carousel',
    description: 'Auto-playing image carousel with manual prev/next controls',
    category: 'ui-animation',
    difficulty: 'intermediate',
    tags: ['useState', 'useEffect', 'setInterval'],
  },
  {
    id: 36,
    title: 'Hoverboard',
    slug: 'hoverboard',
    description: 'A grid of squares that light up in random colors on hover',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['useState', 'mouse events', 'dynamic colors'],
  },
  {
    id: 37,
    title: 'Pokedex',
    slug: 'pokedex',
    description: 'Browse the first 150 Pokemon fetched from the PokeAPI',
    category: 'apps-data',
    difficulty: 'intermediate',
    tags: ['fetch', 'PokeAPI', 'useEffect', 'data fetching'],
  },
  {
    id: 38,
    title: 'Mobile Tab Navigation',
    slug: 'mobile-tab-navigation',
    description: 'Bottom tab navigation bar mimicking a mobile app shell',
    category: 'ui-animation',
    difficulty: 'beginner',
    tags: ['useState', 'tab navigation', 'mobile UI'],
  },
  {
    id: 39,
    title: 'Password Strength Background',
    slug: 'password-strength-background',
    description: 'Background blurs more or less based on password strength',
    category: 'interactivity',
    difficulty: 'intermediate',
    tags: ['useState', 'CSS filter', 'input validation'],
  },
  {
    id: 40,
    title: '3D Background Boxes',
    slug: '3d-background-boxes',
    description: 'A grid of boxes that rotate open to reveal an image behind them',
    category: 'ui-animation',
    difficulty: 'intermediate',
    tags: ['useState', 'CSS 3D transform', 'perspective'],
  },
  {
    id: 41,
    title: 'Verify Account UI',
    slug: 'verify-account-ui',
    description: 'OTP-style input that auto-jumps to the next digit box',
    category: 'interactivity',
    difficulty: 'intermediate',
    tags: ['useRef', 'keyboard events', 'input control'],
  },
  {
    id: 42,
    title: 'Live User Filter',
    slug: 'live-user-filter',
    description: 'Fetches users and filters them in real time as you type',
    category: 'apps-data',
    difficulty: 'intermediate',
    tags: ['fetch', 'useMemo', 'search filter', 'API'],
  },
  {
    id: 43,
    title: 'Feedback UI Design',
    slug: 'feedback-ui-design',
    description: 'Rate your experience with emoji faces then submit feedback',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['useState', 'conditional rendering', 'multi-step UI'],
  },
  {
    id: 44,
    title: 'Custom Range Slider',
    slug: 'custom-range-slider',
    description: 'A styled range slider that updates a label as you drag it',
    category: 'interactivity',
    difficulty: 'beginner',
    tags: ['useState', 'input range', 'CSS styling'],
  },
  {
    id: 45,
    title: 'Netflix Mobile Navigation',
    slug: 'netflix-mobile-navigation',
    description: 'A Netflix-style mobile sidebar navigation with overlay',
    category: 'ui-animation',
    difficulty: 'intermediate',
    tags: ['useState', 'sidebar', 'overlay', 'mobile UI'],
  },
  {
    id: 46,
    title: 'Quiz App',
    slug: 'quiz-app',
    description: 'A multiple-choice quiz with score tracking and a results screen',
    category: 'apps-data',
    difficulty: 'intermediate',
    tags: ['useState', 'conditional rendering', 'game logic'],
  },
  {
    id: 47,
    title: 'Testimonial Box Switcher',
    slug: 'testimonial-box-switcher',
    description: 'Auto-rotates through testimonials with a progress bar timer',
    category: 'ui-animation',
    difficulty: 'intermediate',
    tags: ['useEffect', 'setInterval', 'auto-rotation'],
  },
  {
    id: 48,
    title: 'Random Image Feed',
    slug: 'random-image-feed',
    description: 'Generates a Pinterest-style feed of random images',
    category: 'apps-data',
    difficulty: 'beginner',
    tags: ['Array.from', 'dynamic rendering', 'Unsplash API'],
  },
  {
    id: 49,
    title: 'Todo List',
    slug: 'todo-list',
    description: 'Full CRUD todo list with localStorage persistence',
    category: 'apps-data',
    difficulty: 'intermediate',
    tags: ['useState', 'localStorage', 'CRUD', 'forms'],
  },
  {
    id: 50,
    title: 'Insect Catch Game',
    slug: 'insect-catch-game',
    description: 'Choose an insect then click them as they appear randomly on screen',
    category: 'games',
    difficulty: 'intermediate',
    tags: ['useState', 'useEffect', 'game loop', 'random positioning'],
  },
]

// Helper: get a single project by its slug
export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}

// Helper: get all projects in a category
export function getProjectsByCategory(category: Project['category']): Project[] {
  return projects.filter((p) => p.category === category)
}